### ISSUE TITLE
SMAX Scenarios

### ISSUE THREAD

**Issue by Anri-Lombard** [instadeepai/Mava#1135]
### Please describe what needs to be maintained?
For Smax there is a conflicting environment option that is either intentional or perhaps a mistake.

In the smax config the following environment options are available:
```
env_name: Smax  # Used for logging purposes and selection of the corresponding wrapper.
# Possible tasks:
# 2s3z | 3s5z | 5m_vs_6m | 10m_vs_11m | 27m_vs_30m | 3s5z_vs_3s6z | 3s_vs_5z | 6h_vs_8z | smacv2_5_units | smacv2_10_units | smacv2_20_units
scenario:
  name: HeuristicEnemySMAX
  task_name: 2s3z
```

Notice `3s5z` and `3s_vs_5z`. Perhaps this is a common environment difference I'm not clued up on; is that the case or is this a mistake?

### Describe the outcome you'd like
Clarification on the Smax environments, and since there are no scenarios for it in the scenarios folder some documentation?

### How do we know when maintenance is complete?
Checklist:
- [x] SMAX environments clarified
